### ISSUE TITLE
not working in neovim without using zc or zM firstly.

### ISSUE THREAD

**Issue by ccshao** [arecarn/fold-cycle.vim#11]
In nvim 0.4.3, when opening. a new file, nothing happens without first triger once with zc or zm, or other built-in fold methods. After usage of zc/zo, then CR and BS work nicely as expected. It is quite strange, any ideas on this?

**Comment by ccshao** [comment]
A issue in my init.vim, solved.

**Comment by arecarn** [comment]
glad you figured out 👍
