### ISSUE TITLE
bell

### ISSUE THREAD

**Issue by mikebenfield** [arecarn/fold-cycle.vim#3]
I get a bell if, for instance, I
    :set foldmethod=marker
on this file:
    {{{1 Abc
    ...
then press <CR> with the cursor in the first line. I'm guessing this is not intentional?

**Comment by arecarn** [comment]
I've found the problem and will fix it, but in the mean time you can disable all error bells by putting this snippet in your vimrc

``` viml
if has("autocmd")
    augroup noBells
        autocmd!
        autocmd GUIEnter * set visualbell t_vb=
        autocmd VimEnter * set visualbell t_vb=
    augroup END
endif
```

**Comment by arecarn** [comment]
I think that should do the trick. Let me know how it works. 

also thanks for letting me know about the issue.

**Comment by mikebenfield** [comment]
Works great, thanks!

**Comment by arecarn** [comment]
You're welcome :)
