### ISSUE TITLE
Must I use `zc` to fold a block to use vim-fold-cycle?

### ISSUE THREAD

**Issue by roachsinai** [arecarn/fold-cycle.vim#8]
I use the defautl map `CR` and `BS` to open or close fold.

But I have to use `zc` to fold some code first to let `CR` and `BS` work. If not there is no responce when I press `CR` and `BS`.

## expected behavior

After open a file, `BS` could fold an indent block.

## actual behavior

No response when press `BS` after edit a file, must fold someting use `zc` and then `BS` and `CR` all works.

**Comment by roachsinai** [comment]
Found reason, I have this setting before `set nofoldenable`.

**Comment by arecarn** [comment]
Glad you figured it out :)
